"use client";
import { useMemo, useState } from "react";
import Link from "next/link";
import { ArrowDown, ArrowRight, Check, Clock3, ImagePlus, ShieldCheck, Sparkles } from "lucide-react";
import type { Trend, CategoryOption } from "@/lib/trends";

const steps = [{ icon: ImagePlus, title: "Загрузи селфи", text: "1–10 фотографий при хорошем свете. Чем лучше исходники, тем точнее результат." }, { icon: Sparkles, title: "Выбери образ", text: "Готовый тренд уже содержит нужную стилистику. Промпты писать не нужно." }, { icon: Check, title: "Получи портрет", text: "Генерация обычно занимает около минуты, а результат появится в кабинете." }];
const faq = [{ q: "Сколько фото загружать?", a: "Можно загрузить от 1 до 10 селфи. Лучше использовать несколько фотографий с разных ракурсов без очков и сильных фильтров." }, { q: "Что будет с моими фотографиями?", a: "Исходники нужны только для генерации. Сервис должен хранить их минимально необходимое время. Точные сроки будут указаны в политике конфиденциальности перед запуском оплаты." }, { q: "Можно ли удалить результат?", a: "Да, результат можно удалить из кабинета. Кнопка удаления доступна под каждой генерацией." }, { q: "Сколько ждать?", a: "Обычно около минуты, но время зависит от очереди и внешнего сервиса генерации." }, { q: "Что делать, если результат не понравился?", a: "Сначала попробуйте другой тренд или более качественные исходники. Правила возврата монет будут опубликованы до подключения реальной оплаты." }];
export function HomeClient({ trends, categories }: { trends: Trend[]; categories: CategoryOption[] }) {
  const [active, setActive] = useState("all"); const [openFaq, setOpenFaq] = useState<number | null>(null);
  const visible = useMemo(() => active === "all" ? trends : trends.filter(t => t.categorySlug === active || t.categorySlug === "any"), [active, trends]);
  const examples = trends.slice(0, 3);
  return <main className="flex-1 animate-fade-in px-4 pb-12 pt-6 md:px-8 md:pt-9 lg:px-12"><div className="mx-auto w-full max-w-content">
    <section className="mb-12 flex flex-col justify-between gap-6 border-b border-base-line pb-9 md:flex-row md:items-end"><div className="max-w-[620px]"><p className="eyebrow">AI фотосессии</p><h1 className="mt-3 max-w-[650px] text-[clamp(2rem,4vw,3.65rem)] font-semibold leading-[0.98] tracking-[-0.055em] text-ink">Фото как после съёмки.</h1><p className="mt-3 max-w-[48ch] text-[14px] leading-6 text-ink-muted md:text-[15px]">Выбери образ, загрузи селфи и получи готовый портрет за минуту.</p></div><a href="#trends" className="group inline-flex min-h-11 items-center justify-center gap-2 self-start rounded-full bg-ink px-5 py-3 text-[13px] font-semibold text-base md:self-auto">Выбрать образ <ArrowDown size={15}/></a></section>
    <section className="mb-16"><div className="mb-5"><p className="eyebrow">Просто и быстро</p><h2 className="mt-2 text-2xl font-semibold text-ink">Как это работает</h2></div><div className="grid gap-3 md:grid-cols-3">{steps.map(({icon: Icon, title, text}, i) => <div key={title} className="rounded-2xl border border-base-line bg-base-raised p-5"><div className="flex items-center justify-between"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-base-hover text-ink"><Icon size={18}/></span><span className="text-sm text-ink-faint">0{i+1}</span></div><h3 className="mt-5 font-semibold text-ink">{title}</h3><p className="mt-2 text-sm leading-6 text-ink-muted">{text}</p></div>)}</div></section>
    <section className="mb-16"><div className="mb-5 flex items-end justify-between"><div><p className="eyebrow">Пример результата</p><h2 className="mt-2 text-2xl font-semibold text-ink">До и после</h2></div><span className="text-xs text-ink-faint">Примеры образов</span></div><div className="grid gap-3 md:grid-cols-3">{examples.map((t, i) => <div key={t.slug} className="overflow-hidden rounded-2xl border border-base-line bg-base-raised"><div className="grid grid-cols-2"><div className="flex min-h-48 items-center justify-center bg-base-hover p-4 text-center"><div><div className="mx-auto mb-3 flex h-12 w-12 items-center justify-center rounded-full border border-dashed border-ink-faint text-ink-faint"><ImagePlus size={18}/></div><p className="text-xs text-ink-muted">Ваше селфи</p><p className="mt-1 text-[10px] text-ink-faint">загрузите своё фото</p></div></div><img src={t.image} alt={`Пример образа ${t.name}`} className="min-h-48 w-full object-cover" /></div><div className="flex items-center justify-between p-3"><span className="text-sm font-medium text-ink">{t.name}</span><span className="text-xs text-ink-faint">после</span></div></div>)}</div><p className="mt-3 flex items-center gap-2 text-xs text-ink-faint"><ShieldCheck size={14}/> Справа показан пример стиля. Реальный результат зависит от ваших исходных фото.</p></section>
    <section className="mb-16"><div className="mb-5"><p className="eyebrow">Стоимость</p><h2 className="mt-2 text-2xl font-semibold text-ink">Выберите пакет</h2></div><div className="grid gap-3 md:grid-cols-3">{[[1,119],[3,259],[5,699]].map(([count, price], i) => <div key={count} className={`rounded-2xl border p-5 ${i===1 ? "border-ink/40 bg-base-raised" : "border-base-line bg-base-raised"}`}><p className="text-3xl font-bold text-ink">{count}</p><p className="mt-1 text-sm text-ink-muted">{count === 1 ? "генерация" : "генерации"}</p><p className="mt-5 text-xl font-semibold text-ink">{price} ₽</p><p className="mt-1 text-xs text-ink-faint">5 монет за генерацию</p><Link href="/shop" className="mt-5 flex items-center justify-center rounded-xl bg-ink py-3 text-sm font-semibold text-base">Выбрать пакет</Link></div>)}</div></section>
    <section className="mb-16" id="trends"><div className="mb-4 flex items-end justify-between"><div><p className="eyebrow">Начни здесь</p><h2 className="mt-1.5 text-[20px] font-semibold text-ink">Выбери свой образ</h2></div><span className="text-xs text-ink-faint">{visible.length} стилей</span></div><div className="mb-5 flex gap-2 overflow-x-auto pb-1 no-scrollbar md:flex-wrap">{categories.map(c => <button key={c.slug} type="button" onClick={() => setActive(c.slug)} className={`shrink-0 rounded-full border px-4 py-2 text-[13px] font-medium ${active===c.slug ? "border-ink bg-ink text-base" : "border-base-line bg-base-raised text-ink-muted"}`}>{c.label}</button>)}</div><div className="grid grid-cols-2 gap-3 md:grid-cols-3 lg:grid-cols-4">{visible.map(t => <Link key={t.slug} href={`/trend/${t.slug}`} className="group surface-line relative flex flex-col overflow-hidden rounded-2xl border border-base-line bg-base-raised"><div className="relative overflow-hidden bg-base-hover"><img src={t.image} alt={t.name} className="block aspect-[4/5] w-full object-cover transition duration-700 group-hover:scale-[1.04]"/><div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/10 to-transparent"/><span className="absolute right-2 top-2 rounded-full bg-black/60 px-2 py-1 text-[11px] text-ink">{t.price} 🪙</span><div className="absolute inset-x-0 bottom-0 p-3"><p className="text-sm font-semibold text-ink">{t.name}</p><p className="mt-0.5 line-clamp-1 text-[11px] text-ink-muted">{t.subtitle}</p></div></div><div className="flex items-center justify-between px-3 py-3"><span className="text-xs font-medium text-ink">Попробовать</span><span className="flex h-7 w-7 items-center justify-center rounded-full bg-base-hover text-ink-muted"><ArrowRight size={13}/></span></div></Link>)}</div></section>
    <section className="mb-8"><div className="mb-5"><p className="eyebrow">FAQ</p><h2 className="mt-2 text-2xl font-semibold text-ink">Частые вопросы</h2></div><div className="divide-y divide-base-line rounded-2xl border border-base-line bg-base-raised">{faq.map((item, i) => <button key={item.q} type="button" onClick={() => setOpenFaq(openFaq===i ? null : i)} className="w-full p-5 text-left"><div className="flex items-center justify-between gap-4"><span className="font-medium text-ink">{item.q}</span><span className="text-xl text-ink-faint">{openFaq===i ? "−" : "+"}</span></div>{openFaq===i && <p className="mt-3 max-w-2xl text-sm leading-6 text-ink-muted">{item.a}</p>}</button>)}</div></section>
  </div></main>;
}
